title: "Anusha Jeyaseelan"
email: anushajeyaseelan01@gmail.com
description: >-
  Technical Writer | Cloud, APIs & Developer Infrastructure  
  Sharing insights on documentation, developer tools, and writing for engineers.
baseurl: "" # leave empty for user site
url: "https://anushajeyaseelan.github.io" # replace with your GitHub username
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
